 const productos = [
    {
        id: 1,
        name: "GTA V",
        price: 5000,
        descripcion: 'El sandbox de mundo abierto de excelencia, traído por la mítica companía Rockstar',
        image: "https://www.igta5.com/images/gta-v-five-logo-v-only.png",
        stock: 3,
        categoryId: '1',
    },
    {
        id: 2,
        name: "Red Dead Redemption 2",
        price: 6500,
        descripcion: "La segunda entrega del mítico título Red Dead Redemption",
        image: "https://pngimg.com/uploads/red_dead_redemption/red_dead_redemption_PNG15.png",
        stock: 10,
        categoryId: '1',
    },
    {
        id: 3,
        name: "Counter-Strike: Global Offensive",
        price: 5950,
        descripcion: "La última entrega de la leyenda de Counter-Strike",
        image: "https://1000logos.net/wp-content/uploads/2017/12/CSGO-Logo.png",
        stock: 7,
        categoryId: '1',
    },
    {
        id: 4,
        name: "Satisfactory",
        price: 6700,
        descripcion: "Juego sandbox de construcción de fábricas en un planeta del exterior",
        image: "https://i.imgur.com/WQEHo26.png",
        stock: 5,
        categoryId: '1',
    },
    {
        id: 5,
        name: "Resident Evil 4",
        price: 6300,
        descripcion: "Survival horror clásico que todo hemos jugado",
        image: "https://www.pngitem.com/pimgs/m/85-853690_resident-evil-4-logo-hd-png-download.png",
        stock: 6,
        categoryId: '1',
    },
    {
        id: 6,
        name: "Mafia III",
        price: 6250,
        descripcion: "Mafia III",
        image: "https://www.notebookcheck.net/fileadmin/Notebooks/Sonstiges/Games/Mafia3/logo3.jpg",
        stock: 9,
        categoryId: '1',
    },
    {
        id: 7,
        name: "Nintendo Switch",
        price: 76500,
        descripcion: "Para todas las edades y todos los gustos",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/bo_15px_solid_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/products/hardware/nintendo-switch-red-blue/110478-nintendo-switch-neon-blue-neon-red-package-front-1200x675",
        stock: 5,
        categoryId: '2',
    },
    {
        id: 8,
        name: "PS5",
        price: 62900,
        descripcion: "La gran clásica consola en su quinta versión!",
        image: "https://assets.reedpopcdn.com/ps5-pre-order-header.jpg/BROK/resize/690%3E/format/jpg/quality/75/ps5-pre-order-header.jpg",
        stock: 3,
        categoryId: '2',
    },
    {
        id: 9,
        name: "Xbox Series X",
        price: 6200,
        descripcion: "La competencia directa de Sony! Tecnologías HDR y 4K hasta 8K",

        image: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mRni?ver=a707&q=90&m=6&h=540&w=943&b=%23FF171717&o=f&aim=true",
        stock: 3,
        categoryId: '2',

    },
    {
        id: 10,
        name: "Controles Joy-Con",
        price: 5900,
        descripcion: "Adquiere un set adicional (o dos) de Joy-Con, los controles que hacen posible nuevas maneras de jugar.",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/es_LA/hardware/switch/accessories/joy-con-l-r/thumbnail",
        stock: 4,
        categoryId: '3',

    },
    {
        id: 11,
        name: "Mando para Joy-Con",
        price: 9550,
        descripcion: "Combina el Joy-Con izquierdo y el Joy-Con derecho en un control más grande con este práctico armazón. Te permite cargar el Joy-Con mientras juegas, así no te perderás ni un momento",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/es_LA/hardware/switch/accessories/joy-con-charging-grip/gallery/image01",
        stock: 6,
        categoryId: '3',

    },
    {
        id: 12,
        name: "Funda Portáil para Nintendo Switch ",
        price: 9750,
        descripcion: "Esta funda protegerá a tu Switch de golpes y rayas a la hora de llevarla a otro lado",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/en_US/switch/site-design-update/hardware/switch/accessories/carrying-case-and-screen-protector/gallery/image02",
        stock: 8,
        categoryId: '3',

    },
]
export default productos;